language: scala
scala: 2.13.3
branches:
  only:
  - main
deploy:
  provider: heroku
  api_key:
    secure: sw2VTUupcGNESBgDLlDzD7yZRinEj7ykevOHdkcuOVxmxrau1eui4D2uMZhklBlypBoniGCiiPLEcul1YUbvLTqkOPkR3SpkAWE2fMi4tf+XO6IZuoZHx+o6Pn9jgFG1pDZRZVwpwoqrJ6sDT8gixv4KVTwBwumG6zaNRmI2NgivEd+CUI0ZmDU+l9yaodrpUYROv29+mRW9WSXuiD7lzUNNH/PfJh/xrKsgbPN5nDYVy0vQSCED/esaDS6dzztTFfEft8FUvW+clTOkxacV7hH+31p+kELSyHWd4VTP+6VGcql3qw20AsJ7cSh+kX7QPlJXsQVHuFVexjmk51ldblwoCZUaVMf7K6wH7M9ejdwiyIqsPeidB+bPvcKZIgig0u8moKz139zzWfHKMS6F3RvX9KLndeOjILaxE6zeiiNfspbsT/JqxSfMmrP05qpn5kyDd+TENndZhgAMIRlvlH8XuAtWd/4CtaFZ/XIckIGg1iTDBtUlQjDB0FYpSJ7/8tQH+KVfKttsuqZNvfqX66q0vPinmM+CpV7Vekq9LbOkbp0m/zB1bTbVELqP1cM00bIPmKWii4W4J0Jd7+g6Kf3K4oMD3ftkLkALuCid7DhBlu/GWiSJmlD4ESqjVBLS6qqvF81VLLkY9/mPS/TnTIf5VPWup+Nkny9KGrg7xfY=
  app: autolink365
  on:
    branch: main
