version: '3.1'
services:
  mongo:
    image: mongo:3.4.23-xenial
    ports:
      - 47017:27017
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example